# === USAGE ===
# See https://github.com/uiri/toml for more syntax related information.
#
# File and directory paths are denote with "_fp" (file path) and "_dp"
# (directory path).
#
# Boolean variables (such as "reconstruct_sfm_mvs" or "extract_pan") can be
# toggled with "1" and "0" or "true" and "false".



# === === === === ===
#    Dependencies
# === === === === ===


# === VisSat ===
colmap_vissat_exe_fp = "/path/to/ColmapForVisSat/build/src/exe/colmap"
# VisSat assumes its libraries are in the 'build/__install__/lib' directory
# If you have build VisSat differently and the path differs, you can overwrite it below
colmap_vissat_lib_dp = "/path/to/ColmapForVisSat/build/__install__/lib"

# === MVS, Mesh and Surface Reconstruction Libraries  ===
mve_apps_dp = "/path/to/mve/mve/apps"
texrecon_apps_dp = "/path/to/mvs-texturing/build/apps"
gdmr_bin_dp = "/path/to/pointfusion/pointfusion-0.2.0-Linux/bin"
openmvs_bin_dp = "/path/to/openMVS/build/bin"
colmap_exe_dp = "/path/to/colmap/build/src/exe"

# === Meshlab ===
# Make sure that Meshlab has access to the "meshlab_temp_dp" directory below
# For example, the snap installation of Meshlab may have NO access to /tmp
meshlab_server_fp = "/snap/bin/meshlab.meshlabserver"



# === === === === ===
# Pipeline Workspaces
# === === === === ===
workspace_vissat_dp = "/some/path/to/a/directory"
workspace_ssr_dp = "/some/path/to/a/directory"
meshlab_temp_dp = "/some/path/to/a/directory"



# === === === === ===
#  Pipeline settings
# === === === === ===

# === Computation behavior ===
lazy = 1

# === SfM / MVS Options ===
reconstruct_sfm_mvs = 1
reconstruct_mesh = 1
texture_mesh = 1

meshing_backends = [
    "colmap_poisson",
    "colmap_delaunay",
    "openmvs",
    "mve_fssr",
    "mve_gdmr"
    ]
# Comment symbols can also be used within lists. For example to enable /
# disable specific meshing backends, e.g.
# meshing_backends = [
#    "colmap_poisson",
#    # "colmap_delaunay",
#    "openmvs",
#    # "mve_fssr",
#    "mve_gdmr"
#    ]

texturing_backends = [
    # "openmvs",    # Currently not supported
    "mve"
    ]



# === === === === ===
#  Dataset settings
# === === === === ===


# ===== DFC2019 Track3 dataset =====
#dataset_adapter = "ssr.input_adapters.adapter_DFC2019"
#satellite_image_rgb_tif_dp = "path/to/input/tif/files"
#run_input_adapter = 1
#depth_map_recovery = 1
#skew_correction = 1

# ===== DFC2019 Site 1 =====
#zone_number = 17  # JAX is 17, OMA 15
#hemisphere = "N"
#alt_min = -20.0
#alt_max = 100.0


# ===== IARPA MVS3DM dataset =====
dataset_adapter = "ssr.input_adapters.adapter_MVS3DM"
satellite_image_pan_dp = "/path/to/spacenet-dataset/Hosted-Datasets/MVS_dataset/WV3/PAN"
satellite_image_msi_dp = "/path/to/spacenet-dataset/Hosted-Datasets/MVS_dataset/WV3/MSI"
run_input_adapter = 1
extract_msi = 1
extract_pan = 1
pan_sharpening = 1
depth_map_recovery = 1
skew_correction = 1

# ===== IARPA MVS3DM Site 1 (Used in the VisSat Evaluation) =====
zone_number = 21
hemisphere = "S"
ul_easting = 354035.0
ul_northing = 6182717.0
width = 745.0
height = 682.0
alt_min = -20.0
alt_max = 100.0

# ===== IARPA MVS3DM Site 2 (Used in the VisSat Evaluation) =====
# zone_number = 21
# hemisphere = "S"
# ul_easting = 354984.0
# ul_northing = 6185506.0
# width = 366.0
# height = 350.0
# alt_min = -20.0
# alt_max = 80.0

# ===== IARPA MVS3DM Site 3 (Used in the VisSat Evaluation) =====
# zone_number = 21
# hemisphere = "S"
# ul_easting = 355028.0
# ul_northing = 6187389.0
# width = 426.0
# height = 397.0
# alt_min = -20.0
# alt_max = 90.0
