# === USAGE ===
# See https://github.com/uiri/toml for more syntax related information.
#
# File and directory paths are denote with "_fp" (file path) and "_dp"
# (directory path).
#
# Boolean variables (such as "reconstruct_sfm_mvs" or "extract_pan") can be
# toggled with "1" and "0" or "true" and "false".



# === === === === ===
#    Dependencies
# === === === === ===


# === VisSat ===
colmap_vissat_exe_fp = "/path/to/ColmapForVisSat/build/src/exe/colmap"
# VisSat assumes its libraries are in the 'build/__install__/lib' directory
# If you have build VisSat differently and the path differs, you can overwrite it below
colmap_vissat_lib_dp = "/path/to/ColmapForVisSat/build/__install__/lib"

# === MVS, Mesh and Surface Reconstruction Libraries  ===
mve_apps_dp = "/path/to/mve/mve/apps"
texrecon_apps_dp = "/path/to/mvs-texturing/build/apps"
gdmr_bin_dp = "/path/to/pointfusion/pointfusion-0.2.0-Linux/bin"
openmvs_bin_dp = "/path/to/openMVS/build/bin"
colmap_exe_dp = "/path/to/colmap/build/src/exe"

# === Meshlab ===
# Make sure that Meshlab has access to the "meshlab_temp_dp" directory below
# For example, the snap installation of Meshlab may have NO access to /tmp
meshlab_server_fp = "/snap/bin/meshlab.meshlabserver"



# === === === === ===
# Pipeline Workspaces
# === === === === ===
workspace_images_root_dp = "/some/path/to/a/directory"
workspace_vissat_root_dp = "/some/path/to/a/directory"
workspace_ssr_root_dp = "/some/path/to/a/directory"
meshlab_temp_root_dp = "/some/path/to/a/directory"



# === === === === ===
#  Pipeline settings
# === === === === ===

# === Computation behavior ===
lazy = 1

# === Image Extraction Step ===
run_input_adapter = 1
extract_msi_pan_image_pairs = 1
pan_sharpening = 1

# === Image Extraction Options ===
use_consistent_msi_pan_extraction = 1

# === SfM / MVS Steps ===
reconstruct_sfm_mvs = 1

# === Mesh / Texturing Steps ===
depth_map_recovery = 1
skew_correction = 1
reconstruct_mesh = 1
texture_mesh = 1

meshing_backends = [
    "colmap_poisson",
    "colmap_delaunay",
    "openmvs",
    "mve_fssr",
    "mve_gdmr"
    ]
# Comment symbols can also be used within lists. For example to enable /
# disable specific meshing backends, e.g.
# meshing_backends = [
#    "colmap_poisson",
#    # "colmap_delaunay",
#    "openmvs",
#    # "mve_fssr",
#    "mve_gdmr"
#    ]

texturing_backends = [
    # "openmvs",    # Currently not supported
    "mve"
    ]



# === === === === ===
#  Dataset settings
# === === === === ===


# ===== DFC2019 Track3 dataset =====
#dataset_adapter = "adapter_DFC2019"
#satellite_image_rgb_tif_dp = "path/to/input/tif/files"
#satellite_aoi_data_dp = "path/to/input/DSM.txt/files"

# ===== DFC2019 JAX 004 =====
#aoi_specific_dn = "JAX_004"
#zone_number = 17
#hemisphere = "N"
#aoi_data_fn = "JAX_004_DSM.txt"
#alt_min = -20.0
#alt_max = 100.0

# ===== DFC2019 JAX 068 =====
#aoi_specific_dn = "JAX_068"
#zone_number = 17
#hemisphere = "N"
#aoi_data_fn = "JAX_068_DSM.txt"
#alt_min = -20.0
#alt_max = 100.0

# ===== DFC2019 JAX 214 =====
#aoi_specific_dn = "JAX_214"
#zone_number = 17
#hemisphere = "N"
#aoi_data_fn = "JAX_214_DSM.txt"
#alt_min = -20.0
#alt_max = 100.0

# ===== DFC2019 JAX 260 =====
#aoi_specific_dn = "JAX_260"
#zone_number = 17
#hemisphere = "N"
#aoi_data_fn = "JAX_260_DSM.txt"
#alt_min = -20.0
#alt_max = 100.0

# ===== DFC2019 OMA 342 =====
#aoi_specific_dn = "OMA_342"
#zone_number = 15
#hemisphere = "N"
#aoi_data_fn = "JAX_342_DSM.txt"
#alt_min = -20.0
#alt_max = 100.0

# ===== IARPA MVS3DM dataset =====
dataset_adapter = "adapter_MVS3DM"
satellite_image_pan_dp = "/path/to/spacenet-dataset/Hosted-Datasets/MVS_dataset/WV3/PAN"
satellite_image_msi_dp = "/path/to/spacenet-dataset/Hosted-Datasets/MVS_dataset/WV3/MSI"

# ===== IARPA MVS3DM Site 1 (Used in the VisSat Evaluation) =====
zone_number = 21
hemisphere = "S"
ul_easting = 354035.0
ul_northing = 6182717.0
width = 745.0
height = 682.0
alt_min = -20.0
alt_max = 100.0

# ===== IARPA MVS3DM Site 2 (Used in the VisSat Evaluation) =====
# zone_number = 21
# hemisphere = "S"
# ul_easting = 354984.0
# ul_northing = 6185506.0
# width = 366.0
# height = 350.0
# alt_min = -20.0
# alt_max = 80.0

# ===== IARPA MVS3DM Site 3 (Used in the VisSat Evaluation) =====
# zone_number = 21
# hemisphere = "S"
# ul_easting = 355028.0
# ul_northing = 6187389.0
# width = 426.0
# height = 397.0
# alt_min = -20.0
# alt_max = 90.0


### For debug purposes ###
# [vis_sat_config]
#
# clean_data = false
# crop_image = false
# derive_approx = true
# choose_subset = true
# colmap_sfm_perspective = true
# inspect_sfm_perspective = true
# reparam_depth = true
# colmap_mvs = true
# aggregate_2p5d = true
# aggregate_3d = true
